"""empty message

Revision ID: 95043996faea
Revises: dc5b6ab96fe5
Create Date: 2018-08-29 20:10:28.895902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95043996faea'
down_revision = 'dc5b6ab96fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    # ### end Alembic commands ###
